spring.application.name=USER-SERVICE

server.port=8082

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/payvault_user
spring.datasource.username=root
spring.datasource.password=root

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Actuator
management.endpoints.web.exposure.include=health,info